# Generated by Django 5.1.15 on 2026-08-24 07:36

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0003_remove_distribution_lot_remove_distribution_partner_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('output_product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recipes', to='inventory.product')),
            ],
        ),
        migrations.CreateModel(
            name='RoastBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_output_quantity', models.DecimalField(decimal_places=3, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.001'))])),
                ('roasted_at', models.DateTimeField(auto_now_add=True)),
                ('output_lot', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='produced_by_batch', to='inventory.lot')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='roast_batches', to='production.recipe')),
            ],
        ),
        migrations.CreateModel(
            name='RecipeComponent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ratio_percent', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('input_product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='used_in_recipes', to='inventory.product')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='components', to='production.recipe')),
            ],
            options={
                'unique_together': {('recipe', 'input_product')},
            },
        ),
    ]
