# Generated by Django 5.1.15 on 2026-08-28 06:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0003_candidate_jobopening_application'),
        ('production', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='QualityCheck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result', models.CharField(choices=[('pass', 'Geçti'), ('fail', 'Kaldı')], max_length=10)),
                ('score', models.PositiveIntegerField(blank=True, help_text='Cupping skoru (0-100)', null=True)),
                ('notes', models.TextField(blank=True)),
                ('checked_at', models.DateTimeField(auto_now_add=True)),
                ('batch', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='quality_check', to='production.roastbatch')),
                ('inspector', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='quality_checks', to='hr.employee')),
            ],
        ),
    ]
