# Generated by Django 5.1.15 on 2026-08-26 08:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0002_leavetype_leaverequest'),
    ]

    operations = [
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=32)),
                ('resume_note', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='JobOpening',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('open', 'Açık'), ('closed', 'Kapatıldı'), ('filled', 'Dolduruldu')], default='open', max_length=20)),
                ('opened_at', models.DateTimeField(auto_now_add=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='job_openings', to='hr.department')),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='job_openings', to='hr.position')),
            ],
            options={
                'ordering': ['-opened_at'],
            },
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage', models.CharField(choices=[('applied', 'Başvurdu'), ('screening', 'İnceleniyor'), ('interview', 'Mülakat'), ('offer', 'Teklif'), ('hired', 'İşe Alındı'), ('rejected', 'Reddedildi')], default='applied', max_length=20)),
                ('applied_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='applications', to='hr.candidate')),
                ('job_opening', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='applications', to='hr.jobopening')),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
    ]
