# Generated by Django 5.1.15 on 2026-08-31 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0003_candidate_jobopening_application'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaverequest',
            name='notes',
            field=models.TextField(blank=True),
        ),
    ]
