# Generated by Django 5.1.15 on 2026-08-31 14:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0004_leaverequest_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobopening',
            name='closing_date',
            field=models.DateField(blank=True, null=True, verbose_name='Son Başvuru Tarihi'),
        ),
        migrations.AddField(
            model_name='jobopening',
            name='headcount',
            field=models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Kontenjan'),
        ),
    ]
