# Generated by Django 5.1.15 on 2026-08-21 13:37

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Distribution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel', models.CharField(choices=[('DONATION', 'Donation'), ('DISCOUNT_SALE', 'Discount sale'), ('WASTE', 'Waste')], max_length=20)),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.001'))])),
                ('decided_at', models.DateTimeField(auto_now_add=True)),
                ('note', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['-decided_at', '-pk'],
            },
        ),
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('capacity_kg', models.DecimalField(decimal_places=3, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('contact_email', models.EmailField(max_length=254)),
                ('is_active', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-capacity_kg', 'name'],
            },
        ),
        migrations.AlterField(
            model_name='stockmovement',
            name='quantity',
            field=models.DecimalField(decimal_places=3, max_digits=12),
        ),
        migrations.AddConstraint(
            model_name='stockmovement',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('movement_type', 'IN'), ('quantity__gt', 0)), models.Q(('movement_type__in', ['OUT_DONATION', 'OUT_SALE', 'WASTE']), ('quantity__lt', 0)), _connector='OR'), name='inventory_stock_movement_quantity_sign'),
        ),
        migrations.AddField(
            model_name='distribution',
            name='lot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='distributions', to='inventory.lot'),
        ),
        migrations.AddField(
            model_name='distribution',
            name='partner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='distributions', to='inventory.partner'),
        ),
        migrations.AddConstraint(
            model_name='distribution',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('channel', 'DONATION'), ('partner__isnull', False)), models.Q(('channel__in', ['DISCOUNT_SALE', 'WASTE']), ('partner__isnull', True)), _connector='OR'), name='inventory_distribution_partner_matches_channel'),
        ),
        migrations.AddConstraint(
            model_name='distribution',
            constraint=models.CheckConstraint(condition=models.Q(('quantity__gt', 0)), name='inventory_distribution_quantity_positive'),
        ),
    ]
