# Generated by Django 5.1.15 on 2026-08-24 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_distribution_partner_alter_stockmovement_quantity_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='distribution',
            name='lot',
        ),
        migrations.RemoveField(
            model_name='distribution',
            name='partner',
        ),
        migrations.RemoveConstraint(
            model_name='stockmovement',
            name='inventory_stock_movement_quantity_sign',
        ),
        migrations.AlterField(
            model_name='business',
            name='business_type',
            field=models.CharField(choices=[('supplier', 'Green coffee supplier'), ('wholesale_customer', 'Wholesale customer (cafe)')], max_length=30),
        ),
        migrations.AlterField(
            model_name='stockmovement',
            name='movement_type',
            field=models.CharField(choices=[('IN', 'Stock in'), ('OUT_PRODUCTION', 'Used in production'), ('OUT_SALE', 'Sale out'), ('WASTE', 'Waste')], max_length=20),
        ),
        migrations.AddConstraint(
            model_name='stockmovement',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('movement_type', 'IN'), ('quantity__gt', 0)), models.Q(('movement_type__in', ['OUT_PRODUCTION', 'OUT_SALE', 'WASTE']), ('quantity__lt', 0)), _connector='OR'), name='inventory_stock_movement_quantity_sign'),
        ),
        migrations.DeleteModel(
            name='Distribution',
        ),
        migrations.DeleteModel(
            name='Partner',
        ),
    ]
