# Generated by Django 5.1.15 on 2026-08-25 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_remove_distribution_lot_remove_distribution_partner_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lot',
            name='unit_cost',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Bu lotun birim başına maliyeti (opsiyonel).', max_digits=10, null=True),
        ),
    ]
