# Generated by Django 5.1.15 on 2026-08-27 13:42

from django.db import migrations, models


def classify_internal_roastery(apps, schema_editor):
    Business = apps.get_model('inventory', 'Business')
    Business.objects.filter(
        name='Reflow Coffee Roastery',
        business_type='supplier',
    ).update(business_type='internal')


def restore_roastery_supplier(apps, schema_editor):
    Business = apps.get_model('inventory', 'Business')
    Business.objects.filter(
        name='Reflow Coffee Roastery',
        business_type='internal',
    ).update(business_type='supplier')


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_warehouse_lot_warehouse'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='business',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='business',
            name='business_type',
            field=models.CharField(choices=[('supplier', 'Tedarikçi'), ('wholesale_customer', 'Toptan müşteri (kafe)'), ('internal', 'İç işletme')], max_length=30),
        ),
        migrations.RunPython(classify_internal_roastery, restore_roastery_supplier),
    ]
