# Generated by Django 5.1.15 on 2026-08-28 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_business_is_active_business_notes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='reorder_point',
            field=models.DecimalField(blank=True, decimal_places=3, help_text='Toplam stok bu miktarın altına düşünce otomatik taslak sipariş oluşturulur.', max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='reorder_quantity',
            field=models.DecimalField(blank=True, decimal_places=3, help_text='Otomatik oluşturulacak taslak siparişin miktarı.', max_digits=12, null=True),
        ),
    ]
