"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.0.14.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""

from pathlib import Path
import os
from celery.schedules import crontab
import sentry_sdk

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get('DJANGO_SECRET_KEY')
# SECURITY WARNING: don't run with devbug turned on in production!
DEBUG = os.environ.get('DJANGO_DEBUG', 'False') == 'True'
ALLOWED_HOSTS = os.environ.get('DJANGO_ALLOWED_HOSTS', '').split(',')

CSRF_TRUSTED_ORIGINS = [
    'http://185.22.187.18',
    'http://185.22.187.18:8060',
    'http://185.22.187.18:8000',
    'http://localhost',
    'http://localhost:8060',
]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'inventory',
    'production',
    'sales',
    'ai_layer',
    'purchasing',
    'finance',
    'crm',
    'hr',
    'dashboard',
    'audit',
    'notifications',
    'meetings',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.locale.LocaleMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'config.middleware.ModuleAccessMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

# APP_DIRS yerine açık loader listesi kullanıyoruz. Sebep: APP_DIRS=True,
# DEBUG ne olursa olsun cached.Loader'ı devreye sokuyor — yani her şablon
# düzenlemesinden sonra konteyneri yeniden başlatmak gerekiyordu.
_TEMPLATE_LOADERS = [
    'django.template.loaders.filesystem.Loader',
    'django.template.loaders.app_directories.Loader',
]

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'OPTIONS': {
            'loaders': (
                _TEMPLATE_LOADERS if DEBUG
                else [('django.template.loaders.cached.Loader', _TEMPLATE_LOADERS)]
            ),
            # Her sablonda otomatik yuklu: load ui / load i18n gerekmez.
            'builtins': [
                'dashboard.templatetags.ui',
                'django.templatetags.i18n',
                'django.templatetags.static',
            ],
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.template.context_processors.i18n',
                'notifications.context_processors.notifications_processor',
                'dashboard.context_processors.navigation',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': os.environ.get('POSTGRES_DB'),
        'USER': os.environ.get('POSTGRES_USER'),
        'PASSWORD': os.environ.get('POSTGRES_PASSWORD'),
        'HOST': 'db',
        'PORT': '5432',
    }
}

# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = 'tr'

LANGUAGES = [
    ('tr', 'Türkçe'),
    ('en', 'English'),
]

LOCALE_PATHS = [BASE_DIR / 'locale']

# Celery zaten Europe/Istanbul kullanıyordu; arayüz de aynı dilimde olmalı.
TIME_ZONE = 'Europe/Istanbul'

USE_I18N = True

USE_TZ = True


# Statik dosya ayarları aşağıda, tek yerde toplandı.

# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

CELERY_BROKER_URL = os.environ.get('REDIS_URL', 'redis://redis:6379/0')
CELERY_RESULT_BACKEND = os.environ.get('REDIS_URL', 'redis://redis:6379/0')
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'
CELERY_TIMEZONE = 'Europe/Istanbul'

CELERY_BEAT_SCHEDULE = {
    'nightly-expiry-scan': {
        'task': 'inventory.tasks.scan_lot_freshness',
        'schedule': crontab(hour=2, minute=0),
    },
    'nightly-low-stock-scan': {
        'task': 'purchasing.tasks.scan_low_stock',
        'schedule': crontab(hour=2, minute=30),
    },
    'nightly-defective-return-scan': {
        'task': 'sales.tasks.scan_defective_returns',
        'schedule': crontab(hour=3, minute=0),
    },
}



# Marka adı TEK yerden beslenir. Önceden üç farklı yerde üç farklı
# değer vardı: sayfa başlıklarında 'Reflow Coffee ERP', kabukta
# 'ERP Platform', landing sayfasında '[TBD]'.
SITE_BRAND = 'Reflow Coffee ERP'
SITE_BRAND_SHORT = 'Reflow'
SITE_BRAND_MARK = 'R'
SITE_VERSION = '0.2.0'


def asset_version():
    """
    static/ altındaki en yeni dosyanın zaman damgası — önbellek kırıcı.

    NGINX statikleri `expires 1h` ile servis ediyor; sürüm parametresi olmadan
    CSS/JS değişiklikleri tarayıcıda bir saat boyunca görünmez. Bu değer her
    varlık düzenlemesinde kendiliğinden değişir, elle bump gerektirmez.

    DEBUG'ta her istekte yeniden hesaplanır (≈150 dosya, ölçülemeyecek kadar
    ucuz) — aksi halde CSS düzenleyip sayfayı yenilediğinizde eski dosyayı
    görürdünüz. Üretimde başlangıçta bir kez hesaplanır.
    """
    newest = 0
    static_dir = BASE_DIR / 'static'
    if static_dir.exists():
        for path in static_dir.rglob('*'):
            if path.is_file():
                newest = max(newest, int(path.stat().st_mtime))
    return format(newest, 'x')


ASSET_VERSION = asset_version()

LOGIN_REDIRECT_URL = '/dashboard/'
LOGOUT_REDIRECT_URL = '/'
LOGIN_URL = '/accounts/login/'

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'
STATICFILES_DIRS = [BASE_DIR / 'static']


sentry_sdk.init(
    dsn=os.environ.get('SENTRY_DSN'),
    send_default_pii=False,
    environment='development' if DEBUG else 'production',
)


EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = os.environ.get('EMAIL_HOST_USER')
EMAIL_HOST_PASSWORD = os.environ.get('EMAIL_HOST_PASSWORD')
DEFAULT_FROM_EMAIL = os.environ.get('EMAIL_HOST_USER')
