# Generated by Django 5.1.15 on 2026-08-28 07:17

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0003_alter_customer_customer_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReturnRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.001'))])),
                ('reason', models.CharField(choices=[('customer_changed_mind', 'Müşteri vazgeçti'), ('defective', 'Kusurlu ürün')], max_length=30)),
                ('status', models.CharField(choices=[('requested', 'Talep Edildi'), ('completed', 'Tamamlandı'), ('rejected', 'Reddedildi')], default='requested', max_length=20)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('order_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='return_requests', to='sales.orderitem')),
            ],
        ),
    ]
