# Generated by Django 5.1.15 on 2026-09-01 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0004_returnrequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Beklemede'), ('fulfilled', 'Karşılandı'), ('cancelled', 'İptal edildi')], default='pending', max_length=20),
        ),
    ]
